export const API_ENDPOINTS = {
  LOGIN: '/users/login',
  REGISTER: '/users/register',
  CREATE_GROUP: '/groups/create',
  GET_GROUPS: '/groups',
  GET_GROUP_DETAIL: (groupId: number) => `/groups/${groupId}`,
  CREATE_EXPENSE: '/expenses/create',
  UPLOAD_GROUP_IMAGE: '/uploads/groups',
  DELETE_GROUP: (groupId: number) => `/groups/${groupId}`,
  SEND_INVITATION: '/invitations/send',
  GET_INVITATIONS: '/invitations/all',
  ACCEPT_INVITATION: '/invitations/accept',
  REJECT_INVITATION: '/invitations/reject',
  ADD_GUEST_MEMBER: (groupId: number) => `/groups/${groupId}/members/guest`,
  CLAIMABLE_GUESTS: '/users/claimable-guests',
  CLAIM_GUEST_MEMBERSHIP: '/users/claim-guest',
  CREATE_PAYMENT: '/payments/create',
  UPDATE_PAYMENT: (paymentId: number) => `/payments/${paymentId}`,
  DELETE_PAYMENT: (paymentId: number) => `/payments/${paymentId}`,
};
