#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function parseEnv(content) {
  const lines = content.split(/\r?\n/);
  const result = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.substring(0, eq).trim();
    let val = trimmed.substring(eq + 1).trim();
    // remove surrounding quotes
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    result[key] = val;
  }
  return result;
}

function loadDotEnv(filePath) {
  try {
    const full = path.resolve(process.cwd(), filePath);
    if (!fs.existsSync(full)) return {};
    const content = fs.readFileSync(full, 'utf8');
    return parseEnv(content);
  } catch (err) {
    console.error('Failed to read', filePath, err);
    return {};
  }
}

function pickKeys(src) {
  const out = {};
  for (const k of Object.keys(src)) {
    out[k] = src[k];
  }
  return out;
}

function normalize(vars) {
  const out = {};
  for (const k of Object.keys(vars)) {
    // Support VITE_ prefix or plain names. Strip VITE_ to keep keys stable.
    const key = k.startsWith('VITE_') ? k.substring(5) : k;
    out[key] = vars[k];
  }
  return out;
}

function generateTS(envVars, production) {
  const entries = Object.keys(envVars)
    .sort()
    .map((k) => {
      const v = envVars[k];
      // try to detect booleans and numbers
      if (v === 'true' || v === 'false') return `  ${k}: ${v}`;
      if (!isNaN(v) && v !== '') return `  ${k}: ${v}`;
      // otherwise string
      const escaped = v.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\$');
      return `  ${k}: \`${escaped}\``;
    })
    .join(',\n');

  return `// This file is auto-generated by scripts/generate-env.js - do not edit by hand\nexport const environment = {\n  production: ${production},\n${entries}\n};\n`;
}

function main() {
  const arg = (process.argv[2] || 'development').toLowerCase();
  const isProd = arg === 'production' || arg === 'prod';
  const projectRoot = process.cwd();

  const envFile = isProd ? '.env.production' : '.env.development';

  const envFromFile = loadDotEnv(envFile);
  const envFromProcess = pickKeys(process.env);

  // merge: process.env takes precedence
  const merged = Object.assign({}, envFromFile, envFromProcess);

  // normalize keys (strip VITE_ prefix)
  const normalizedAll = normalize(merged);

  // Filter: only export keys that were intentionally meant for the client.
  // Keep keys that originally had VITE_ prefix or that are in the allowlist.
  const allowlist = new Set(['API_URL', 'NODE_ENV', 'MODE']);
  const normalized = {};
  for (const rawKey of Object.keys(merged)) {
    const key = rawKey.startsWith('VITE_') ? rawKey.substring(5) : rawKey;
    if (rawKey.startsWith('VITE_') || allowlist.has(key)) {
      normalized[key] = normalizedAll[key];
    }
  }

  // ensure at least API_URL exists (common case)
  if (!normalized.API_URL && normalized.VITE_API_URL) normalized.API_URL = normalized.VITE_API_URL;

  const outDir = path.join(projectRoot, 'src', 'environments');
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

  const envTs = generateTS(normalized, false);
  const envProdTs = generateTS(normalized, true);

  fs.writeFileSync(path.join(outDir, 'environment.ts'), envTs, 'utf8');
  fs.writeFileSync(path.join(outDir, 'environment.prod.ts'), envProdTs, 'utf8');

  console.log(`Generated environment files for ${isProd ? 'production' : 'development'}`);

  // If building for production, ensure required keys exist
  if (isProd) {
    const hasApiUrl = !!(
      normalized.API_URL ||
      normalized.VITE_API_URL ||
      normalizedAll.API_URL ||
      normalizedAll.VITE_API_URL
    );
    if (!hasApiUrl) {
      // If running in GitHub Actions as a pull_request from a fork, secrets/envs may be unavailable.
      const githubEvent = process.env.GITHUB_EVENT_NAME || '';
      const isGithubPr = githubEvent === 'pull_request' || !!process.env.GITHUB_HEAD_REF;
      if (isGithubPr) {
        console.warn(
          'Warning: Missing API_URL or VITE_API_URL, but running inside a GitHub pull_request build — skipping strict production validation.',
        );
      } else {
        console.error(
          'Missing required environment variable: API_URL or VITE_API_URL (required for production builds)',
        );
        process.exit(2);
      }
    }
  }
}

main();
